### ISSUE TITLE
StandardTagFactory can't handle @inheritdoc tag

### ISSUE THREAD

**Issue by naffiq** [phpDocumentor/ReflectionDocBlock#116]
Hello and thank you for this great package.

I have an issue processing `@inheritdoc` tags in StandardTagFactory  on line 116. I believe that this is because `@inheritdoc` tag doesn't have any body and because all classes are final I can't redefine it's behavior.

And btw, does this lib handle `@inheritdoc` at all?

**Comment by jaapio** [comment]
No we do not handle the `@inheritdoc`. In this library. The tag should be available as a generic tag. So when you get the tags from a docblock I think it should be there.

Since inheritance requires a element tree to be able to fetch the inherited docs we are not using it here. This library only processes a docblock and is not aware of any structure. 

If you have more questions please feel free to ask :-)

**Comment by naffiq** [comment]
@jaapio 

So does it mean if phpdoc section has nothing, but `@inheritdoc`, then lib will crash?
I'll can provide test case, if needed :)

Thanks for response

**Comment by jaapio** [comment]
That was not indented. if you could provide a unit test that would be very nice!
