### ISSUE TITLE
How to remove a tag?

### ISSUE THREAD

**Issue by TomasVotruba** [phpDocumentor/ReflectionDocBlock#124]
I need to remove specific tag.

I'm aware of method `addTag(Tag $tag)`, but there is no way to remove one (without reflection and setter).

**Comment by jaapio** [comment]
I think the only way is to create a custom `TagFactory` that doesn't have the full set so it doesn't process that kind of tags.

Is there a specific usecase why you need this? We would like to keep the DocBlock interface as is since it is kind of immutable currently. Only extra information can be added. Otherwise it is up the the consumer to ignore certain tags.

**Comment by TomasVotruba** [comment]
> ... immutable currently. Only extra information can be added

That's kinda contradicting. If it would be immutable, it would be consistent, but only adding tags and not removing doesn't.
 
I need to remove annotation. I used PHP CS Fixer's `DocBlock` class that allowed this, but this package is bit more advanced in cleaning the annotation content.

At the moment I'm using 4-lines property reflection: https://github.com/RectorPHP/Rector/pull/108/files#diff-d5f0fbb1e400ad3f2475118f0acdc2ebR133

It would be nice to remove it, but I'll understand if you don't want to add option to remove tag.

**Comment by jaapio** [comment]
> That's kinda contradicting. If it would be immutable it would be consistent, but only adding tags and not removing makes it ambiguous in it's purpose.

I understand that it's a bit contradicting. But cloning the object over any over again would have a huge impact on the memory usage. We have to redo the benchmarking but on php5 this was a no go since this code is executed so many times when analyzing a full application. 

Maybe a custom formater when printing the tags again could help you out?

**Comment by TomasVotruba** [comment]
Why cloning what object? I only need to remove tags, that's all.

> Maybe a custom formater when printing the tags again could help you out?

I need to modify docblock on various places before printing it once back.

This is exactly what respects current `addTag()` API: https://github.com/phpDocumentor/ReflectionDocBlock/pull/125

**Comment by TomasVotruba** [comment]
Any updates?

**Comment by TomasVotruba** [comment]
Resolved by #125

**Comment by TomasVotruba** [comment]
Any plans for releasing this? Patch would be fine.
I'd like to remove those reflection stuff from my code.

**Comment by jaapio** [comment]
https://github.com/phpDocumentor/ReflectionDocBlock/releases/tag/4.2.0 here you go sir.

**Comment by TomasVotruba** [comment]
Thank you man!
