### ISSUE TITLE
Types wrongfully determined as Void_

### ISSUE THREAD

**Issue by afraca** [phpDocumentor/ReflectionDocBlock#160]
When parsing a docblock generated by https://github.com/barryvdh/laravel-ide-helper , I recently noticed how arguments would always get the type Void_  . When rebuilding the docblock, suddenly you have `void $foo` everywhere. I'll try to get some more insight in what's happening and a clear reproducable case, but this report is to let you know in case I don't get around to it anymore.

------
` * @method static \Foo\Bar baz(array $context = array())`  , will get this:
```
51 => Method {#1625 ▼
      #name: "method"
      -methodName: "category"
      -arguments: array:1 [▼
        0 => array:2 [▼
          "name" => "context"
          "type" => Void_ {#1624}
        ]
      ]
      -isStatic: true
      -returnType: Compound {#1629 ▶}
      #description: Description {#1626 ▶}
    }
```

edit:

Think this is the problem (from quick glance), at least when NO type hint is provided:
https://github.com/phpDocumentor/ReflectionDocBlock/blob/master/src/DocBlock/Tags/Method.php#L141

It would *not* explain the problem with `array $context = array()` like above.

**Comment by afraca** [comment]
Also, any default values (like above with `$context`) will get removed. That's a different issue though

**Comment by jaapio** [comment]
Thanks for reaching out to us. 
I just pushed a change that addresses the wrong default for arguments. I tried to reproduce your issue with the void type of the given example. But I cannot reproduce it. Since this issue is a few years old and a lot has been changed. And I expect this to be fixed meanwhile. 

Please create a new issue if this is still not working for you. We will try to help.
