### ISSUE TITLE
render of Description encloses tags in {}

### ISSUE THREAD

**Issue by ancpru** [phpDocumentor/ReflectionDocBlock#168]
Is this really meant to be that way:

the render method of Description allows to pass a formatter to format a the tag, but always encloses the result in braces:

```
    /**
     * Renders this description as a string where the provided formatter will format the tags in the expected string
     * format.
     */
    public function render(?Formatter $formatter = null): string
    {
        if ($formatter === null) {
            $formatter = new PassthroughFormatter();
        }

        $tags = [];
        foreach ($this->tags as $tag) {
            $tags[] = '{' . $formatter->format($tag) . '}';
        }

        return vsprintf($this->bodyTemplate, $tags);
    }
```

This would mean that some kind of re-parsing is always needed to get rid of them. Is it meant to be that way? Somehow I think it would make more sense to add the braces inside the default formatter. This way custom formatters could output whatever they want without having to deal with the braces again. 

**Edit***

I made this change:

https://github.com/phpDocumentor/ReflectionDocBlock/pull/171

By this change it's easy to override the default DescriptionFactory without having to do a copy&paste-implementation: override create in DescriptionFactory, let parent::create create a default Description and then create a custom description object using what's in the originally created. 

This way it's easy to overcome the behavior of always created {} in the standard Description output which I do not really would like to have there when I use the formatter to turn inline tags into markdown syntax.

**Comment by jaapio** [comment]
Hi @ancpru,

Sorry for the late response, we have been busy with other things than just phpDocumentor and it's libraries.
All tags included in a description MUST be enclosed by `{}` because we expect them to be first class citizens of the description. The docblock parser is expecting them to be in `{}` so that should not be an issue. It would be very helpful if you could provide more context why you want to change this behavior.

For example

```
This is a description {@some-tag having a description}. This is where the rest of the description continues
```

The only way to know where the description of the tag ends is to wrap the tag in some way.  But I would like to understand your use case. So we can discuss if a change is needed.

**Comment by jaapio** [comment]
Think this one is solved, and can be closed.
