### ISSUE TITLE
Support 'static' modifier for magic properties as well?

### ISSUE THREAD

**Issue by ghost** [phpDocumentor/ReflectionDocBlock#69]
Hello

I see that support for the very useful `static` keyword inside the `@method` tag for static magic methods already seems to be present. However, am I correct in assuming that there currently is no equivalent for `@property`, `@property-read` and `@property-write`? I'm currently using a (somewhat half-baked) custom docblock parser, but would much rather move to a more compliant parser like this project, I think this is the only item that I currently have found no replacement for ;-).

Thanks in advance

**Comment by jaapio** [comment]
I think static for a property is not supported because `@propery` allows you to document 'magic' properties. But php doesn't support a magic static property since there is no such thing in php like __getstatic. 

I don't know why you need it since php doesn't support it in any way. Therefor I'm closing this issue. But feel free to add an example and reopen this issue.
