### ISSUE TITLE
PHP Fatal Error when Using ReflectionDocBlock as a dependency

### ISSUE THREAD

**Issue by danhanly** [phpDocumentor/ReflectionDocBlock#80]
I'm getting the below issue in my project:

```
PHP Fatal error:  phpDocumentor\Reflection\DocBlock\Tags\BaseTag cannot implement phpDocumentor\Reflection\DocBlock\Tag - it is not an interface in /vendor/phpdocumentor/reflection-docblock/src/DocBlock/Tags/BaseTag.php on line 21
```

**Comment by greg0ire** [comment]
So do I , and very oddly, it's only when using php 5.5 . Other builds work just fine. Composer resolves to version 3.1.0

**Comment by greg0ire** [comment]
In my case, the problem was that I'm using phpunit as an external tools, but I also require (indirectly) phpunit in my project. Using `vendor/bin/phpunit` solved it.

**Comment by miscellainiac** [comment]
I'm having the same error, though it only manifest in a Drupal 6 -> 8 migration project where we are tying to perform some post migration operations; this worked at some point and is actually a big blocker to a site launch. I am open to other suggestions, like removing phpunit from the dependencies or something like that...

**Comment by IslandUsurper** [comment]
This is really strange. I'm using Ansible to set up my project on both Vagrant for development and AWS for staging and production. This error only happens on AWS. Same OS (Ubuntu Trusty x64), same PHP versions (5.5.9-1ubuntu4.19), same ReflectionDocBlock version (3.1.0), same scripts, but only one of them throws an error. As the project is a Drupal site, the command that throws the error is `drush cc drush`, which I would not expect to even run phpunit or anything related to it. Maybe it's hitting the autoloader . . .
. . .
Oh golly. I'm using the drush.phar downloadable, because that was the easiest way to install it with Ansible. Follow along this [stacktrace](https://github.com/phpDocumentor/ReflectionDocBlock/files/501632/drush-stacktrace.txt) with me. Line 21, `Consolidation\AnnotatedCommand\Parser\Internal\CommandDocBlockParser3->createDocBlock()` calls `phpDocumentor\Reflection\DocBlockFactory->create()` from my project's vendor directory instead of drush's. And then, line 27, `ReflectinoMethod->__construct()` invokes the autoloader, which goes back to drush's vendor directory, and I have no idea what version of ReflectionDocBlock they put in the phar, but it's not the one I downloaded, so things are broken.

Still doesn't explain why it works on Vagrant, when it should be the same version of Drush.
. . .
Oh, it's not. :frowning: Vagrant had Drush 8.1.3, while AWS got 8.1.5. Forcing the Vagrant machine to get Drush again causes the problem to show up there.

**Comment by SoboLAN** [comment]
@danhanly I've found a solution to this. I simply added this requirement in my `composer.json`:

`"phpdocumentor/reflection-docblock": "2.0.*"`

This downgraded the dependency from `3.1` to `2.0` and it worked. (I'm using phpunit 4.8).

If you still have this issue, try it out.

**Comment by jaapio** [comment]
It looks like some other projects depending on phpdocumentor/reflection-docblock where conflicting in some situations. I cannot reproduce this with our own code. If you still experience any issues with this please reopen this issue with more information how to reproduce it.

**Comment by m4olivei** [comment]
Hi there. I'm getting this same error. `phpdocumentor/reflection-docblock` is getting installed at version 4.3.0 via `phpunit/phpunit`:

```
$ composer why -t phpdocumentor/reflection-docblock
phpdocumentor/reflection-docblock 4.3.0 With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
└──phpspec/prophecy 1.7.5 (requires phpdocumentor/reflection-docblock ^2.0|^3.0.2|^4.0)
   └──phpunit/phpunit 6.5.7 (requires phpspec/prophecy ^1.7)
```

Composer version 1.6.3 and PHP version 7.2.2 if that's relevant. I noticed that I get this weird folder structure in `vendor/phpdocumentor/reflection-docblock` which causes the error:

```
$ cd vendor/phpdocumentor/reflection-docblock
$ tree -d
.
`-- src
    |-- DocBlock
    |   `-- Tags
    |       |-- Factory
    |       |-- Formatter
    |       `-- Reference
    `-- phpDocumentor
        `-- Reflection
            `-- DocBlock
                |-- Tag
                `-- Type
```
So there is this weird `src/phpDocumentor/Reflection` folder in there, which isn't part of this repository, that appears to be mixing up the autoloader. It appears to be loading up the `src/phpDocumentor/Reflection/DocBlock/Tag.php` file which is indeed a class and not an interface, which would explain the error message.

Any insight?

Also I can't see a way to re-open this issue.

**Comment by m4olivei** [comment]
Never mind, false alarm,

In our case we had some weird composer caching in our jobs. We were trying to cache the vendor directory and had some combination of events contribute to effectively having the 2.x and 4.x code in the vendor directory at the same time.
