### ISSUE TITLE
Support for callable definitions

### ISSUE THREAD

**Issue by kelunik** [phpDocumentor/ReflectionDocBlock#83]
There should be support for callable definitions as types.

``` php
/**
 * Summary.
 *
 * @param callable(Throwable|Exception $error) $callback
 *         Callback executed upon uncaught errors.
 */
```

Currently this just makes the block fail to parse entirely.

**Comment by staabm** [comment]
the signature should also support return types, e.g. 

```
/**
 * Summary.
 *
 * @param callable(Throwable|Exception $error):MyReturnType $callback
 *         Callback executed upon uncaught errors.
 */
```

**Comment by kelunik** [comment]
This will complicate the parser, as spaces can't be used to separate the arguments anymore.

```
callable(Throwable|Exception $error, string $foo): MyReturnType
                            ^       ^             ^
```

**Comment by jaapio** [comment]
@mvriel I think we should add this in the future. It makes a lot of sense to have a description for the exprected callable.

**Comment by jaapio** [comment]
When looking at this feature request it seemed very plausible to have this. On the other hand It would be strange to add arguments to the callable type of our type resolver. Since the php type doesn't have any arguments. 

I don't know yet if and how we can implement this. Typically the arguments should be part of a some how complex description. Since we cannot modify the callable type for this. It looks like our current architecture is not able to support this use case. 

I will leave this open for further discussion. Maybe we will find a solution when PRS-5 is continued

**Comment by jaapio** [comment]
Update on this one, we added support for callables in the type resolver. This will be part of our next release.
